export {default as HomeView} from "../views/HomeView.vue"
export {default as RegisterView} from "../views/RegisterView.vue"
export {default as LoginView} from "../views/LoginView.vue"
export {default as ArticleDetailesView } from "../views/ArticleDetailesView.vue"
export {default as CreateFormView} from "../views/CreateFormView.vue"
export {default as EditArticleView} from "../views/EditArticleview.vue"